# bunfig.toml

[test]
# The directory to search for tests in.
#
# Defaults to "."
# Can be a single path, or a list of paths.
#
# root = "."

# Preload scripts before running tests
#
# Can be a single path, or a list of paths.
#
# preload = ["./scripts/preload.ts"]

# The tsconfig file to use for path aliases & compilation
#
# Defaults to "tsconfig.json" or "jsconfig.json"
tsconfig = "packages/backend/tsconfig.json"
