apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: aaelink
data:
  NODE_ENV: production
  PORT: "3001"
  DATABASE_URL: postgresql://aaelink:secure_password_123@postgres:5432/aaelink
  REDIS_URL: redis://:redis_password_123@redis:6379
  MINIO_ENDPOINT: http://minio:9000
  MINIO_ACCESS_KEY: minioadmin
  MINIO_SECRET_KEY: minioadmin123
  MINIO_BUCKET: aaelink-files
  N8N_URL: http://n8n:5678

---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: aaelink
type: Opaque
data:
  JWT_SECRET: eW91cl9qd3Rfc2VjcmV0X2tleV9oZXJl # your_jwt_secret_key_here
  CSRF_SECRET: eW91cl9jc3JmX3NlY3JldF9rZXlfaGVyZQ== # your_csrf_secret_key_here

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: aaelink
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: aaelink/backend:latest
        ports:
        - containerPort: 3001
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: aaelink
spec:
  selector:
    app: backend
  ports:
  - port: 3001
    targetPort: 3001
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: aaelink
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
