// ── Emoji data + helpers (shared by EmojiPicker and the composer) ──────────
// Extracted from EmojiPicker.tsx to keep that component under the 250-line cap.
// This is a dataset file; it is intentionally long. The public API
// (EMOJI_DATA, emojiMatches, getFrequent/pushFrequent, getSkinTone/setSkinTone/
// applySkinTone, SKIN_TONES, CATEGORIES, CATEGORY_ICONS) is kept stable.

export interface EmojiEntry {
  emoji: string
  name: string
  category: string
  /** Short colon-aliases used for `:alias:` search (e.g. '+1', 'thumbsup'). */
  aliases?: string[]
  /** True when this emoji accepts a Fitzpatrick skin-tone modifier. */
  skinTonable?: boolean
}

export const EMOJI_DATA: EmojiEntry[] = [
  // ── Smileys ──────────────────────────────────────────────────────────────
  { emoji: '😀', name: 'grinning', category: 'Smileys', aliases: ['grinning'] },
  { emoji: '😃', name: 'smiley', category: 'Smileys', aliases: ['smiley'] },
  { emoji: '😄', name: 'smile', category: 'Smileys', aliases: ['smile'] },
  { emoji: '😁', name: 'grin', category: 'Smileys', aliases: ['grin'] },
  { emoji: '😆', name: 'laughing', category: 'Smileys', aliases: ['laughing', 'satisfied'] },
  { emoji: '😅', name: 'sweat smile', category: 'Smileys', aliases: ['sweat_smile'] },
  { emoji: '😂', name: 'joy', category: 'Smileys', aliases: ['joy', 'lol'] },
  { emoji: '🤣', name: 'rofl', category: 'Smileys', aliases: ['rofl', 'rolling_on_the_floor_laughing'] },
  { emoji: '🥲', name: 'smiling tear', category: 'Smileys', aliases: ['smiling_face_with_tear'] },
  { emoji: '😊', name: 'blush', category: 'Smileys', aliases: ['blush'] },
  { emoji: '😇', name: 'innocent', category: 'Smileys', aliases: ['innocent'] },
  { emoji: '🙂', name: 'slightly smiling', category: 'Smileys', aliases: ['slightly_smiling_face'] },
  { emoji: '🙃', name: 'upside down', category: 'Smileys', aliases: ['upside_down_face'] },
  { emoji: '😉', name: 'wink', category: 'Smileys', aliases: ['wink'] },
  { emoji: '😌', name: 'relieved', category: 'Smileys', aliases: ['relieved'] },
  { emoji: '😍', name: 'heart eyes', category: 'Smileys', aliases: ['heart_eyes'] },
  { emoji: '🥰', name: 'smiling with hearts', category: 'Smileys', aliases: ['smiling_face_with_three_hearts'] },
  { emoji: '😘', name: 'kissing heart', category: 'Smileys', aliases: ['kissing_heart'] },
  { emoji: '😗', name: 'kissing', category: 'Smileys', aliases: ['kissing'] },
  { emoji: '😙', name: 'kissing smiling eyes', category: 'Smileys', aliases: ['kissing_smiling_eyes'] },
  { emoji: '😚', name: 'kissing closed eyes', category: 'Smileys', aliases: ['kissing_closed_eyes'] },
  { emoji: '😋', name: 'yum', category: 'Smileys', aliases: ['yum'] },
  { emoji: '😛', name: 'stuck out tongue', category: 'Smileys', aliases: ['stuck_out_tongue'] },
  { emoji: '😜', name: 'winking tongue', category: 'Smileys', aliases: ['stuck_out_tongue_winking_eye'] },
  { emoji: '🤪', name: 'zany', category: 'Smileys', aliases: ['zany_face'] },
  { emoji: '😝', name: 'squinting tongue', category: 'Smileys', aliases: ['stuck_out_tongue_closed_eyes'] },
  { emoji: '🤑', name: 'money mouth', category: 'Smileys', aliases: ['money_mouth_face'] },
  { emoji: '😎', name: 'sunglasses', category: 'Smileys', aliases: ['sunglasses', 'cool'] },
  { emoji: '🤩', name: 'star struck', category: 'Smileys', aliases: ['star_struck'] },
  { emoji: '🥳', name: 'partying', category: 'Smileys', aliases: ['partying_face'] },
  { emoji: '😏', name: 'smirk', category: 'Smileys', aliases: ['smirk'] },
  { emoji: '😒', name: 'unamused', category: 'Smileys', aliases: ['unamused'] },
  { emoji: '😞', name: 'disappointed', category: 'Smileys', aliases: ['disappointed'] },
  { emoji: '😔', name: 'pensive', category: 'Smileys', aliases: ['pensive'] },
  { emoji: '😟', name: 'worried', category: 'Smileys', aliases: ['worried'] },
  { emoji: '😕', name: 'confused', category: 'Smileys', aliases: ['confused'] },
  { emoji: '🙁', name: 'slightly frowning', category: 'Smileys', aliases: ['slightly_frowning_face'] },
  { emoji: '😣', name: 'persevere', category: 'Smileys', aliases: ['persevere'] },
  { emoji: '😖', name: 'confounded', category: 'Smileys', aliases: ['confounded'] },
  { emoji: '😫', name: 'tired', category: 'Smileys', aliases: ['tired_face'] },
  { emoji: '😩', name: 'weary', category: 'Smileys', aliases: ['weary'] },
  { emoji: '🥺', name: 'pleading', category: 'Smileys', aliases: ['pleading_face'] },
  { emoji: '😢', name: 'cry', category: 'Smileys', aliases: ['cry'] },
  { emoji: '😭', name: 'sob', category: 'Smileys', aliases: ['sob'] },
  { emoji: '😤', name: 'triumph', category: 'Smileys', aliases: ['triumph'] },
  { emoji: '😠', name: 'angry', category: 'Smileys', aliases: ['angry'] },
  { emoji: '😡', name: 'rage', category: 'Smileys', aliases: ['rage', 'pout'] },
  { emoji: '🤬', name: 'cursing', category: 'Smileys', aliases: ['cursing_face', 'swearing'] },
  { emoji: '🤯', name: 'exploding head', category: 'Smileys', aliases: ['exploding_head', 'mind_blown'] },
  { emoji: '😳', name: 'flushed', category: 'Smileys', aliases: ['flushed'] },
  { emoji: '🥵', name: 'hot face', category: 'Smileys', aliases: ['hot_face'] },
  { emoji: '🥶', name: 'cold face', category: 'Smileys', aliases: ['cold_face'] },
  { emoji: '😱', name: 'scream', category: 'Smileys', aliases: ['scream'] },
  { emoji: '😨', name: 'fearful', category: 'Smileys', aliases: ['fearful'] },
  { emoji: '😰', name: 'cold sweat', category: 'Smileys', aliases: ['cold_sweat'] },
  { emoji: '😥', name: 'disappointed relieved', category: 'Smileys', aliases: ['disappointed_relieved'] },
  { emoji: '😓', name: 'sweat', category: 'Smileys', aliases: ['sweat'] },
  { emoji: '🤗', name: 'hugging', category: 'Smileys', aliases: ['hugging_face'] },
  { emoji: '🤔', name: 'thinking', category: 'Smileys', aliases: ['thinking', 'thinking_face'] },
  { emoji: '🤭', name: 'hand over mouth', category: 'Smileys', aliases: ['hand_over_mouth'] },
  { emoji: '🤫', name: 'shushing', category: 'Smileys', aliases: ['shushing_face'] },
  { emoji: '🤥', name: 'lying', category: 'Smileys', aliases: ['lying_face'] },
  { emoji: '😶', name: 'no mouth', category: 'Smileys', aliases: ['no_mouth'] },
  { emoji: '😐', name: 'neutral', category: 'Smileys', aliases: ['neutral_face'] },
  { emoji: '😑', name: 'expressionless', category: 'Smileys', aliases: ['expressionless'] },
  { emoji: '😬', name: 'grimacing', category: 'Smileys', aliases: ['grimacing'] },
  { emoji: '🙄', name: 'eye roll', category: 'Smileys', aliases: ['roll_eyes'] },
  { emoji: '😯', name: 'hushed', category: 'Smileys', aliases: ['hushed'] },
  { emoji: '😦', name: 'frowning open', category: 'Smileys', aliases: ['frowning'] },
  { emoji: '😮', name: 'open mouth', category: 'Smileys', aliases: ['open_mouth', 'wow'] },
  { emoji: '😲', name: 'astonished', category: 'Smileys', aliases: ['astonished'] },
  { emoji: '🥱', name: 'yawning', category: 'Smileys', aliases: ['yawning_face'] },
  { emoji: '😴', name: 'sleeping', category: 'Smileys', aliases: ['sleeping'] },
  { emoji: '🤤', name: 'drooling', category: 'Smileys', aliases: ['drooling_face'] },
  { emoji: '😪', name: 'sleepy', category: 'Smileys', aliases: ['sleepy'] },
  { emoji: '😵', name: 'dizzy', category: 'Smileys', aliases: ['dizzy_face'] },
  { emoji: '🤐', name: 'zipper mouth', category: 'Smileys', aliases: ['zipper_mouth_face'] },
  { emoji: '🥴', name: 'woozy', category: 'Smileys', aliases: ['woozy_face'] },
  { emoji: '🤢', name: 'nauseated', category: 'Smileys', aliases: ['nauseated_face'] },
  { emoji: '🤮', name: 'vomiting', category: 'Smileys', aliases: ['vomiting_face', 'puke'] },
  { emoji: '🤧', name: 'sneezing', category: 'Smileys', aliases: ['sneezing_face'] },
  { emoji: '😷', name: 'mask', category: 'Smileys', aliases: ['mask'] },
  { emoji: '🤒', name: 'thermometer face', category: 'Smileys', aliases: ['face_with_thermometer', 'sick'] },
  { emoji: '🤕', name: 'head bandage', category: 'Smileys', aliases: ['face_with_head_bandage'] },
  { emoji: '🤠', name: 'cowboy', category: 'Smileys', aliases: ['cowboy_hat_face'] },
  { emoji: '🤓', name: 'nerd', category: 'Smileys', aliases: ['nerd_face'] },
  { emoji: '🧐', name: 'monocle', category: 'Smileys', aliases: ['monocle_face'] },
  { emoji: '😈', name: 'smiling imp', category: 'Smileys', aliases: ['smiling_imp'] },
  { emoji: '👿', name: 'angry imp', category: 'Smileys', aliases: ['imp'] },
  { emoji: '🤡', name: 'clown', category: 'Smileys', aliases: ['clown_face'] },
  { emoji: '💀', name: 'skull', category: 'Smileys', aliases: ['skull'] },
  { emoji: '👻', name: 'ghost', category: 'Smileys', aliases: ['ghost'] },
  { emoji: '👽', name: 'alien', category: 'Smileys', aliases: ['alien'] },
  { emoji: '🤖', name: 'robot', category: 'Smileys', aliases: ['robot', 'robot_face'] },
  { emoji: '💩', name: 'poop', category: 'Smileys', aliases: ['poop', 'shit', 'hankey'] },
  { emoji: '🫡', name: 'salute', category: 'Smileys', aliases: ['saluting_face', 'salute'] },
  { emoji: '🫠', name: 'melting', category: 'Smileys', aliases: ['melting_face'] },
  { emoji: '🫥', name: 'dotted line', category: 'Smileys', aliases: ['dotted_line_face'] },

  // ── People ───────────────────────────────────────────────────────────────
  { emoji: '👶', name: 'baby', category: 'People', aliases: ['baby'], skinTonable: true },
  { emoji: '🧒', name: 'child', category: 'People', aliases: ['child'], skinTonable: true },
  { emoji: '👦', name: 'boy', category: 'People', aliases: ['boy'], skinTonable: true },
  { emoji: '👧', name: 'girl', category: 'People', aliases: ['girl'], skinTonable: true },
  { emoji: '🧑', name: 'person', category: 'People', aliases: ['adult', 'person'], skinTonable: true },
  { emoji: '👨', name: 'man', category: 'People', aliases: ['man'], skinTonable: true },
  { emoji: '👩', name: 'woman', category: 'People', aliases: ['woman'], skinTonable: true },
  { emoji: '🧓', name: 'older person', category: 'People', aliases: ['older_adult'], skinTonable: true },
  { emoji: '👴', name: 'old man', category: 'People', aliases: ['older_man'], skinTonable: true },
  { emoji: '👵', name: 'old woman', category: 'People', aliases: ['older_woman'], skinTonable: true },
  { emoji: '🧑‍💻', name: 'technologist', category: 'People', aliases: ['technologist', 'developer'] },
  { emoji: '🧑‍🔧', name: 'mechanic', category: 'People', aliases: ['mechanic'] },
  { emoji: '🧑‍🏫', name: 'teacher', category: 'People', aliases: ['teacher'] },
  { emoji: '🧑‍🚀', name: 'astronaut', category: 'People', aliases: ['astronaut'] },
  { emoji: '👮', name: 'police', category: 'People', aliases: ['police_officer', 'cop'], skinTonable: true },
  { emoji: '🕵️', name: 'detective', category: 'People', aliases: ['detective', 'spy'], skinTonable: true },
  { emoji: '💂', name: 'guard', category: 'People', aliases: ['guard'], skinTonable: true },
  { emoji: '👷', name: 'construction worker', category: 'People', aliases: ['construction_worker'], skinTonable: true },
  { emoji: '🤴', name: 'prince', category: 'People', aliases: ['prince'], skinTonable: true },
  { emoji: '👸', name: 'princess', category: 'People', aliases: ['princess'], skinTonable: true },
  { emoji: '🦸', name: 'superhero', category: 'People', aliases: ['superhero'], skinTonable: true },
  { emoji: '🦹', name: 'supervillain', category: 'People', aliases: ['supervillain'], skinTonable: true },
  { emoji: '🤵', name: 'person in tuxedo', category: 'People', aliases: ['person_in_tuxedo'], skinTonable: true },
  { emoji: '👰', name: 'person with veil', category: 'People', aliases: ['person_with_veil', 'bride'], skinTonable: true },
  { emoji: '🤰', name: 'pregnant', category: 'People', aliases: ['pregnant_woman'], skinTonable: true },
  { emoji: '🧑‍🍼', name: 'feeding baby', category: 'People', aliases: ['person_feeding_baby'] },
  { emoji: '🎅', name: 'santa', category: 'People', aliases: ['santa'], skinTonable: true },
  { emoji: '🤦', name: 'facepalm', category: 'People', aliases: ['facepalm', 'face_palm'], skinTonable: true },
  { emoji: '🤷', name: 'shrug', category: 'People', aliases: ['shrug'], skinTonable: true },
  { emoji: '🙋', name: 'raising hand', category: 'People', aliases: ['raising_hand'], skinTonable: true },
  { emoji: '🙆', name: 'ok gesture', category: 'People', aliases: ['ok_woman', 'gesturing_ok'], skinTonable: true },
  { emoji: '🙅', name: 'no gesture', category: 'People', aliases: ['no_good', 'gesturing_no'], skinTonable: true },
  { emoji: '💁', name: 'tipping hand', category: 'People', aliases: ['information_desk_person', 'tipping_hand'], skinTonable: true },
  { emoji: '🙇', name: 'bowing', category: 'People', aliases: ['bow', 'bowing'], skinTonable: true },
  { emoji: '🚶', name: 'walking', category: 'People', aliases: ['walking', 'pedestrian'], skinTonable: true },
  { emoji: '🏃', name: 'running', category: 'People', aliases: ['running', 'runner'], skinTonable: true },
  { emoji: '💃', name: 'dancer', category: 'People', aliases: ['dancer'], skinTonable: true },
  { emoji: '🕺', name: 'man dancing', category: 'People', aliases: ['man_dancing'], skinTonable: true },

  // ── Gestures & Body (skin-tonable) ────────────────────────────────────────
  { emoji: '👍', name: 'thumbs up', category: 'Gestures', aliases: ['+1', 'thumbsup', 'thumbs_up'], skinTonable: true },
  { emoji: '👎', name: 'thumbs down', category: 'Gestures', aliases: ['-1', 'thumbsdown', 'thumbs_down'], skinTonable: true },
  { emoji: '👌', name: 'ok hand', category: 'Gestures', aliases: ['ok_hand'], skinTonable: true },
  { emoji: '🤌', name: 'pinched fingers', category: 'Gestures', aliases: ['pinched_fingers'], skinTonable: true },
  { emoji: '🤏', name: 'pinching hand', category: 'Gestures', aliases: ['pinching_hand'], skinTonable: true },
  { emoji: '✌️', name: 'peace', category: 'Gestures', aliases: ['v', 'victory', 'peace'], skinTonable: true },
  { emoji: '🤞', name: 'crossed fingers', category: 'Gestures', aliases: ['crossed_fingers'], skinTonable: true },
  { emoji: '🫰', name: 'finger heart', category: 'Gestures', aliases: ['hand_with_index_finger_and_thumb_crossed'], skinTonable: true },
  { emoji: '🤟', name: 'love you gesture', category: 'Gestures', aliases: ['love_you_gesture'], skinTonable: true },
  { emoji: '🤘', name: 'rock on', category: 'Gestures', aliases: ['metal', 'sign_of_the_horns'], skinTonable: true },
  { emoji: '🤙', name: 'call me', category: 'Gestures', aliases: ['call_me_hand'], skinTonable: true },
  { emoji: '👈', name: 'point left', category: 'Gestures', aliases: ['point_left'], skinTonable: true },
  { emoji: '👉', name: 'point right', category: 'Gestures', aliases: ['point_right'], skinTonable: true },
  { emoji: '👆', name: 'point up', category: 'Gestures', aliases: ['point_up_2'], skinTonable: true },
  { emoji: '👇', name: 'point down', category: 'Gestures', aliases: ['point_down'], skinTonable: true },
  { emoji: '☝️', name: 'index pointing up', category: 'Gestures', aliases: ['point_up'], skinTonable: true },
  { emoji: '✋', name: 'raised hand', category: 'Gestures', aliases: ['raised_hand', 'hand'], skinTonable: true },
  { emoji: '🤚', name: 'raised back of hand', category: 'Gestures', aliases: ['raised_back_of_hand'], skinTonable: true },
  { emoji: '🖐️', name: 'hand splayed', category: 'Gestures', aliases: ['raised_hand_with_fingers_splayed'], skinTonable: true },
  { emoji: '🖖', name: 'vulcan salute', category: 'Gestures', aliases: ['vulcan_salute', 'spock'], skinTonable: true },
  { emoji: '👋', name: 'wave', category: 'Gestures', aliases: ['wave'], skinTonable: true },
  { emoji: '🤝', name: 'handshake', category: 'Gestures', aliases: ['handshake'], skinTonable: true },
  { emoji: '👏', name: 'clap', category: 'Gestures', aliases: ['clap'], skinTonable: true },
  { emoji: '🙌', name: 'raised hands', category: 'Gestures', aliases: ['raised_hands'], skinTonable: true },
  { emoji: '👐', name: 'open hands', category: 'Gestures', aliases: ['open_hands'], skinTonable: true },
  { emoji: '🤲', name: 'palms up together', category: 'Gestures', aliases: ['palms_up_together'], skinTonable: true },
  { emoji: '🙏', name: 'pray', category: 'Gestures', aliases: ['pray', 'thanks'], skinTonable: true },
  { emoji: '✊', name: 'raised fist', category: 'Gestures', aliases: ['fist', 'fist_raised'], skinTonable: true },
  { emoji: '👊', name: 'fist bump', category: 'Gestures', aliases: ['fist_oncoming', 'punch'], skinTonable: true },
  { emoji: '🤛', name: 'left fist', category: 'Gestures', aliases: ['fist_left'], skinTonable: true },
  { emoji: '🤜', name: 'right fist', category: 'Gestures', aliases: ['fist_right'], skinTonable: true },
  { emoji: '🫶', name: 'heart hands', category: 'Gestures', aliases: ['heart_hands'], skinTonable: true },
  { emoji: '🫳', name: 'palm down hand', category: 'Gestures', aliases: ['palm_down_hand'], skinTonable: true },
  { emoji: '🫴', name: 'palm up hand', category: 'Gestures', aliases: ['palm_up_hand'], skinTonable: true },
  { emoji: '💪', name: 'muscle', category: 'Gestures', aliases: ['muscle', 'flex'], skinTonable: true },
  { emoji: '🦾', name: 'mechanical arm', category: 'Gestures', aliases: ['mechanical_arm'] },
  { emoji: '✍️', name: 'writing hand', category: 'Gestures', aliases: ['writing_hand'], skinTonable: true },
  { emoji: '👀', name: 'eyes', category: 'Gestures', aliases: ['eyes'] },
  { emoji: '👁️', name: 'eye', category: 'Gestures', aliases: ['eye'] },
  { emoji: '🧠', name: 'brain', category: 'Gestures', aliases: ['brain'] },
  { emoji: '👅', name: 'tongue', category: 'Gestures', aliases: ['tongue'] },
  { emoji: '👂', name: 'ear', category: 'Gestures', aliases: ['ear'], skinTonable: true },
  { emoji: '👃', name: 'nose', category: 'Gestures', aliases: ['nose'], skinTonable: true },

  // ── Hearts ────────────────────────────────────────────────────────────────
  { emoji: '❤️', name: 'red heart', category: 'Hearts', aliases: ['heart', 'red_heart'] },
  { emoji: '🩷', name: 'pink heart', category: 'Hearts', aliases: ['pink_heart'] },
  { emoji: '🧡', name: 'orange heart', category: 'Hearts', aliases: ['orange_heart'] },
  { emoji: '💛', name: 'yellow heart', category: 'Hearts', aliases: ['yellow_heart'] },
  { emoji: '💚', name: 'green heart', category: 'Hearts', aliases: ['green_heart'] },
  { emoji: '💙', name: 'blue heart', category: 'Hearts', aliases: ['blue_heart'] },
  { emoji: '🩵', name: 'light blue heart', category: 'Hearts', aliases: ['light_blue_heart'] },
  { emoji: '💜', name: 'purple heart', category: 'Hearts', aliases: ['purple_heart'] },
  { emoji: '🤎', name: 'brown heart', category: 'Hearts', aliases: ['brown_heart'] },
  { emoji: '🖤', name: 'black heart', category: 'Hearts', aliases: ['black_heart'] },
  { emoji: '🩶', name: 'grey heart', category: 'Hearts', aliases: ['grey_heart', 'gray_heart'] },
  { emoji: '🤍', name: 'white heart', category: 'Hearts', aliases: ['white_heart'] },
  { emoji: '💔', name: 'broken heart', category: 'Hearts', aliases: ['broken_heart'] },
  { emoji: '❤️‍🔥', name: 'heart on fire', category: 'Hearts', aliases: ['heart_on_fire'] },
  { emoji: '❤️‍🩹', name: 'mending heart', category: 'Hearts', aliases: ['mending_heart'] },
  { emoji: '💖', name: 'sparkling heart', category: 'Hearts', aliases: ['sparkling_heart'] },
  { emoji: '💗', name: 'growing heart', category: 'Hearts', aliases: ['heartpulse'] },
  { emoji: '💓', name: 'beating heart', category: 'Hearts', aliases: ['heartbeat'] },
  { emoji: '💞', name: 'revolving hearts', category: 'Hearts', aliases: ['revolving_hearts'] },
  { emoji: '💕', name: 'two hearts', category: 'Hearts', aliases: ['two_hearts'] },
  { emoji: '💘', name: 'heart with arrow', category: 'Hearts', aliases: ['cupid'] },
  { emoji: '💝', name: 'heart with ribbon', category: 'Hearts', aliases: ['gift_heart'] },
  { emoji: '💟', name: 'heart decoration', category: 'Hearts', aliases: ['heart_decoration'] },
  { emoji: '💌', name: 'love letter', category: 'Hearts', aliases: ['love_letter'] },
  { emoji: '💯', name: 'hundred', category: 'Hearts', aliases: ['100', 'hundred'] },
  { emoji: '💋', name: 'kiss mark', category: 'Hearts', aliases: ['kiss'] },

  // ── Animals & Nature ──────────────────────────────────────────────────────
  { emoji: '🐶', name: 'dog', category: 'Animals', aliases: ['dog'] },
  { emoji: '🐱', name: 'cat', category: 'Animals', aliases: ['cat'] },
  { emoji: '🐭', name: 'mouse', category: 'Animals', aliases: ['mouse'] },
  { emoji: '🐹', name: 'hamster', category: 'Animals', aliases: ['hamster'] },
  { emoji: '🐰', name: 'rabbit', category: 'Animals', aliases: ['rabbit'] },
  { emoji: '🦊', name: 'fox', category: 'Animals', aliases: ['fox_face', 'fox'] },
  { emoji: '🐻', name: 'bear', category: 'Animals', aliases: ['bear'] },
  { emoji: '🐼', name: 'panda', category: 'Animals', aliases: ['panda_face', 'panda'] },
  { emoji: '🐨', name: 'koala', category: 'Animals', aliases: ['koala'] },
  { emoji: '🐯', name: 'tiger', category: 'Animals', aliases: ['tiger'] },
  { emoji: '🦁', name: 'lion', category: 'Animals', aliases: ['lion'] },
  { emoji: '🐮', name: 'cow', category: 'Animals', aliases: ['cow'] },
  { emoji: '🐷', name: 'pig', category: 'Animals', aliases: ['pig'] },
  { emoji: '🐸', name: 'frog', category: 'Animals', aliases: ['frog'] },
  { emoji: '🐵', name: 'monkey', category: 'Animals', aliases: ['monkey_face'] },
  { emoji: '🙈', name: 'see no evil', category: 'Animals', aliases: ['see_no_evil'] },
  { emoji: '🐔', name: 'chicken', category: 'Animals', aliases: ['chicken'] },
  { emoji: '🐧', name: 'penguin', category: 'Animals', aliases: ['penguin'] },
  { emoji: '🐦', name: 'bird', category: 'Animals', aliases: ['bird'] },
  { emoji: '🦆', name: 'duck', category: 'Animals', aliases: ['duck'] },
  { emoji: '🦅', name: 'eagle', category: 'Animals', aliases: ['eagle'] },
  { emoji: '🦉', name: 'owl', category: 'Animals', aliases: ['owl'] },
  { emoji: '🐝', name: 'bee', category: 'Animals', aliases: ['bee', 'honeybee'] },
  { emoji: '🦋', name: 'butterfly', category: 'Animals', aliases: ['butterfly'] },
  { emoji: '🐌', name: 'snail', category: 'Animals', aliases: ['snail'] },
  { emoji: '🐢', name: 'turtle', category: 'Animals', aliases: ['turtle'] },
  { emoji: '🐍', name: 'snake', category: 'Animals', aliases: ['snake'] },
  { emoji: '🐙', name: 'octopus', category: 'Animals', aliases: ['octopus'] },
  { emoji: '🐳', name: 'whale', category: 'Animals', aliases: ['whale'] },
  { emoji: '🐬', name: 'dolphin', category: 'Animals', aliases: ['dolphin'] },
  { emoji: '🐟', name: 'fish', category: 'Animals', aliases: ['fish'] },
  { emoji: '🦈', name: 'shark', category: 'Animals', aliases: ['shark'] },
  { emoji: '🐴', name: 'horse', category: 'Animals', aliases: ['horse'] },
  { emoji: '🦄', name: 'unicorn', category: 'Animals', aliases: ['unicorn'] },
  { emoji: '🐘', name: 'elephant', category: 'Animals', aliases: ['elephant'] },
  { emoji: '🌸', name: 'cherry blossom', category: 'Animals', aliases: ['cherry_blossom'] },
  { emoji: '🌺', name: 'hibiscus', category: 'Animals', aliases: ['hibiscus'] },
  { emoji: '🌻', name: 'sunflower', category: 'Animals', aliases: ['sunflower'] },
  { emoji: '🌹', name: 'rose', category: 'Animals', aliases: ['rose'] },
  { emoji: '🌷', name: 'tulip', category: 'Animals', aliases: ['tulip'] },
  { emoji: '🌳', name: 'tree', category: 'Animals', aliases: ['deciduous_tree', 'tree'] },
  { emoji: '🌲', name: 'evergreen', category: 'Animals', aliases: ['evergreen_tree'] },
  { emoji: '🌵', name: 'cactus', category: 'Animals', aliases: ['cactus'] },
  { emoji: '🍀', name: 'four leaf clover', category: 'Animals', aliases: ['four_leaf_clover'] },
  { emoji: '🍃', name: 'leaves', category: 'Animals', aliases: ['leaves'] },
  { emoji: '🌿', name: 'herb', category: 'Animals', aliases: ['herb'] },

  // ── Food & Drink ──────────────────────────────────────────────────────────
  { emoji: '🍏', name: 'green apple', category: 'Food', aliases: ['green_apple'] },
  { emoji: '🍎', name: 'apple', category: 'Food', aliases: ['apple'] },
  { emoji: '🍐', name: 'pear', category: 'Food', aliases: ['pear'] },
  { emoji: '🍊', name: 'tangerine', category: 'Food', aliases: ['tangerine', 'orange'] },
  { emoji: '🍋', name: 'lemon', category: 'Food', aliases: ['lemon'] },
  { emoji: '🍌', name: 'banana', category: 'Food', aliases: ['banana'] },
  { emoji: '🍉', name: 'watermelon', category: 'Food', aliases: ['watermelon'] },
  { emoji: '🍇', name: 'grapes', category: 'Food', aliases: ['grapes'] },
  { emoji: '🍓', name: 'strawberry', category: 'Food', aliases: ['strawberry'] },
  { emoji: '🫐', name: 'blueberries', category: 'Food', aliases: ['blueberries'] },
  { emoji: '🍒', name: 'cherries', category: 'Food', aliases: ['cherries'] },
  { emoji: '🍑', name: 'peach', category: 'Food', aliases: ['peach'] },
  { emoji: '🥭', name: 'mango', category: 'Food', aliases: ['mango'] },
  { emoji: '🍍', name: 'pineapple', category: 'Food', aliases: ['pineapple'] },
  { emoji: '🥥', name: 'coconut', category: 'Food', aliases: ['coconut'] },
  { emoji: '🥝', name: 'kiwi', category: 'Food', aliases: ['kiwi_fruit'] },
  { emoji: '🍅', name: 'tomato', category: 'Food', aliases: ['tomato'] },
  { emoji: '🥑', name: 'avocado', category: 'Food', aliases: ['avocado'] },
  { emoji: '🌽', name: 'corn', category: 'Food', aliases: ['corn'] },
  { emoji: '🥕', name: 'carrot', category: 'Food', aliases: ['carrot'] },
  { emoji: '🥔', name: 'potato', category: 'Food', aliases: ['potato'] },
  { emoji: '🍞', name: 'bread', category: 'Food', aliases: ['bread'] },
  { emoji: '🥐', name: 'croissant', category: 'Food', aliases: ['croissant'] },
  { emoji: '🥨', name: 'pretzel', category: 'Food', aliases: ['pretzel'] },
  { emoji: '🧀', name: 'cheese', category: 'Food', aliases: ['cheese'] },
  { emoji: '🍳', name: 'fried egg', category: 'Food', aliases: ['fried_egg', 'cooking'] },
  { emoji: '🥞', name: 'pancakes', category: 'Food', aliases: ['pancakes'] },
  { emoji: '🥓', name: 'bacon', category: 'Food', aliases: ['bacon'] },
  { emoji: '🍔', name: 'hamburger', category: 'Food', aliases: ['hamburger', 'burger'] },
  { emoji: '🍟', name: 'fries', category: 'Food', aliases: ['fries'] },
  { emoji: '🍕', name: 'pizza', category: 'Food', aliases: ['pizza'] },
  { emoji: '🌭', name: 'hot dog', category: 'Food', aliases: ['hotdog'] },
  { emoji: '🌮', name: 'taco', category: 'Food', aliases: ['taco'] },
  { emoji: '🌯', name: 'burrito', category: 'Food', aliases: ['burrito'] },
  { emoji: '🍜', name: 'ramen', category: 'Food', aliases: ['ramen', 'noodles'] },
  { emoji: '🍝', name: 'spaghetti', category: 'Food', aliases: ['spaghetti', 'pasta'] },
  { emoji: '🍣', name: 'sushi', category: 'Food', aliases: ['sushi'] },
  { emoji: '🍱', name: 'bento', category: 'Food', aliases: ['bento'] },
  { emoji: '🍚', name: 'rice', category: 'Food', aliases: ['rice'] },
  { emoji: '🍦', name: 'soft ice cream', category: 'Food', aliases: ['icecream'] },
  { emoji: '🍩', name: 'doughnut', category: 'Food', aliases: ['doughnut', 'donut'] },
  { emoji: '🍪', name: 'cookie', category: 'Food', aliases: ['cookie'] },
  { emoji: '🎂', name: 'birthday cake', category: 'Food', aliases: ['birthday', 'cake'] },
  { emoji: '🍰', name: 'shortcake', category: 'Food', aliases: ['cake_slice'] },
  { emoji: '🍫', name: 'chocolate', category: 'Food', aliases: ['chocolate_bar'] },
  { emoji: '🍿', name: 'popcorn', category: 'Food', aliases: ['popcorn'] },
  { emoji: '☕', name: 'coffee', category: 'Food', aliases: ['coffee'] },
  { emoji: '🍵', name: 'tea', category: 'Food', aliases: ['tea'] },
  { emoji: '🧋', name: 'bubble tea', category: 'Food', aliases: ['bubble_tea', 'boba'] },
  { emoji: '🍺', name: 'beer', category: 'Food', aliases: ['beer'] },
  { emoji: '🍻', name: 'clinking beers', category: 'Food', aliases: ['beers'] },
  { emoji: '🍷', name: 'wine', category: 'Food', aliases: ['wine_glass'] },
  { emoji: '🥂', name: 'champagne toast', category: 'Food', aliases: ['clinking_glasses', 'cheers'] },
  { emoji: '🍸', name: 'cocktail', category: 'Food', aliases: ['cocktail'] },

  // ── Activities & Sports ───────────────────────────────────────────────────
  { emoji: '⚽', name: 'soccer', category: 'Activities', aliases: ['soccer', 'football'] },
  { emoji: '🏀', name: 'basketball', category: 'Activities', aliases: ['basketball'] },
  { emoji: '🏈', name: 'american football', category: 'Activities', aliases: ['football_american'] },
  { emoji: '⚾', name: 'baseball', category: 'Activities', aliases: ['baseball'] },
  { emoji: '🎾', name: 'tennis', category: 'Activities', aliases: ['tennis'] },
  { emoji: '🏐', name: 'volleyball', category: 'Activities', aliases: ['volleyball'] },
  { emoji: '🏉', name: 'rugby', category: 'Activities', aliases: ['rugby_football'] },
  { emoji: '🎱', name: 'pool 8 ball', category: 'Activities', aliases: ['8ball', 'pool'] },
  { emoji: '🏓', name: 'ping pong', category: 'Activities', aliases: ['ping_pong', 'table_tennis'] },
  { emoji: '🏸', name: 'badminton', category: 'Activities', aliases: ['badminton'] },
  { emoji: '🥅', name: 'goal net', category: 'Activities', aliases: ['goal_net'] },
  { emoji: '⛳', name: 'golf', category: 'Activities', aliases: ['golf'] },
  { emoji: '🏹', name: 'archery', category: 'Activities', aliases: ['bow_and_arrow', 'archery'] },
  { emoji: '🎣', name: 'fishing', category: 'Activities', aliases: ['fishing_pole_and_fish'] },
  { emoji: '🥊', name: 'boxing', category: 'Activities', aliases: ['boxing_glove'] },
  { emoji: '🥋', name: 'martial arts', category: 'Activities', aliases: ['martial_arts_uniform'] },
  { emoji: '🛹', name: 'skateboard', category: 'Activities', aliases: ['skateboard'] },
  { emoji: '🛼', name: 'roller skate', category: 'Activities', aliases: ['roller_skate'] },
  { emoji: '⛸️', name: 'ice skate', category: 'Activities', aliases: ['ice_skate'] },
  { emoji: '🏂', name: 'snowboard', category: 'Activities', aliases: ['snowboarder'], skinTonable: true },
  { emoji: '🏋️', name: 'weight lifting', category: 'Activities', aliases: ['weight_lifter', 'lifting'], skinTonable: true },
  { emoji: '🤸', name: 'cartwheel', category: 'Activities', aliases: ['cartwheel'], skinTonable: true },
  { emoji: '🤾', name: 'handball', category: 'Activities', aliases: ['handball'], skinTonable: true },
  { emoji: '🏊', name: 'swimming', category: 'Activities', aliases: ['swimmer'], skinTonable: true },
  { emoji: '🚴', name: 'cycling', category: 'Activities', aliases: ['bicyclist', 'cycling'], skinTonable: true },
  { emoji: '🧗', name: 'climbing', category: 'Activities', aliases: ['climbing'], skinTonable: true },
  { emoji: '🤺', name: 'fencing', category: 'Activities', aliases: ['fencer'] },
  { emoji: '🏆', name: 'trophy', category: 'Activities', aliases: ['trophy'] },
  { emoji: '🥇', name: 'gold medal', category: 'Activities', aliases: ['1st_place_medal', 'gold_medal'] },
  { emoji: '🥈', name: 'silver medal', category: 'Activities', aliases: ['2nd_place_medal', 'silver_medal'] },
  { emoji: '🥉', name: 'bronze medal', category: 'Activities', aliases: ['3rd_place_medal', 'bronze_medal'] },
  { emoji: '🏅', name: 'sports medal', category: 'Activities', aliases: ['medal_sports'] },
  { emoji: '🎖️', name: 'military medal', category: 'Activities', aliases: ['medal_military'] },
  { emoji: '🎮', name: 'video game', category: 'Activities', aliases: ['video_game', 'gaming'] },
  { emoji: '🕹️', name: 'joystick', category: 'Activities', aliases: ['joystick'] },
  { emoji: '🎲', name: 'die', category: 'Activities', aliases: ['game_die', 'dice'] },
  { emoji: '🎯', name: 'target', category: 'Activities', aliases: ['dart', 'target', 'bullseye'] },
  { emoji: '🎳', name: 'bowling', category: 'Activities', aliases: ['bowling'] },
  { emoji: '🎤', name: 'microphone', category: 'Activities', aliases: ['microphone', 'mic'] },
  { emoji: '🎧', name: 'headphones', category: 'Activities', aliases: ['headphones'] },
  { emoji: '🎸', name: 'guitar', category: 'Activities', aliases: ['guitar'] },
  { emoji: '🎹', name: 'piano', category: 'Activities', aliases: ['musical_keyboard', 'piano'] },
  { emoji: '🥁', name: 'drum', category: 'Activities', aliases: ['drum'] },
  { emoji: '🎺', name: 'trumpet', category: 'Activities', aliases: ['trumpet'] },
  { emoji: '🎨', name: 'artist palette', category: 'Activities', aliases: ['art', 'palette'] },
  { emoji: '🎬', name: 'clapper', category: 'Activities', aliases: ['clapper', 'movie'] },
  { emoji: '🎭', name: 'performing arts', category: 'Activities', aliases: ['performing_arts', 'theater'] },
  { emoji: '🎪', name: 'circus', category: 'Activities', aliases: ['circus_tent'] },

  // ── Travel & Places ───────────────────────────────────────────────────────
  { emoji: '🚗', name: 'car', category: 'Travel', aliases: ['car', 'red_car'] },
  { emoji: '🚕', name: 'taxi', category: 'Travel', aliases: ['taxi'] },
  { emoji: '🚙', name: 'suv', category: 'Travel', aliases: ['blue_car', 'suv'] },
  { emoji: '🚌', name: 'bus', category: 'Travel', aliases: ['bus'] },
  { emoji: '🚓', name: 'police car', category: 'Travel', aliases: ['police_car'] },
  { emoji: '🚑', name: 'ambulance', category: 'Travel', aliases: ['ambulance'] },
  { emoji: '🚒', name: 'fire engine', category: 'Travel', aliases: ['fire_engine'] },
  { emoji: '🚜', name: 'tractor', category: 'Travel', aliases: ['tractor'] },
  { emoji: '🏎️', name: 'race car', category: 'Travel', aliases: ['racing_car'] },
  { emoji: '🏍️', name: 'motorcycle', category: 'Travel', aliases: ['motorcycle'] },
  { emoji: '🚲', name: 'bicycle', category: 'Travel', aliases: ['bike', 'bicycle'] },
  { emoji: '🛴', name: 'scooter', category: 'Travel', aliases: ['kick_scooter'] },
  { emoji: '✈️', name: 'airplane', category: 'Travel', aliases: ['airplane', 'flight'] },
  { emoji: '🚀', name: 'rocket', category: 'Travel', aliases: ['rocket', 'ship_it'] },
  { emoji: '🛸', name: 'ufo', category: 'Travel', aliases: ['flying_saucer', 'ufo'] },
  { emoji: '🚁', name: 'helicopter', category: 'Travel', aliases: ['helicopter'] },
  { emoji: '⛵', name: 'sailboat', category: 'Travel', aliases: ['sailboat'] },
  { emoji: '🚤', name: 'speedboat', category: 'Travel', aliases: ['speedboat'] },
  { emoji: '🛳️', name: 'passenger ship', category: 'Travel', aliases: ['passenger_ship', 'cruise'] },
  { emoji: '🚂', name: 'locomotive', category: 'Travel', aliases: ['steam_locomotive', 'train'] },
  { emoji: '🚆', name: 'train', category: 'Travel', aliases: ['train2'] },
  { emoji: '🚇', name: 'metro', category: 'Travel', aliases: ['metro', 'subway'] },
  { emoji: '🚦', name: 'traffic light', category: 'Travel', aliases: ['vertical_traffic_light'] },
  { emoji: '🗺️', name: 'world map', category: 'Travel', aliases: ['world_map', 'map'] },
  { emoji: '🗿', name: 'moai', category: 'Travel', aliases: ['moyai', 'moai'] },
  { emoji: '🗽', name: 'statue of liberty', category: 'Travel', aliases: ['statue_of_liberty'] },
  { emoji: '🗼', name: 'tokyo tower', category: 'Travel', aliases: ['tokyo_tower'] },
  { emoji: '🏰', name: 'castle', category: 'Travel', aliases: ['european_castle', 'castle'] },
  { emoji: '🏠', name: 'house', category: 'Travel', aliases: ['house', 'home'] },
  { emoji: '🏢', name: 'office building', category: 'Travel', aliases: ['office', 'building'] },
  { emoji: '🏥', name: 'hospital', category: 'Travel', aliases: ['hospital'] },
  { emoji: '🏦', name: 'bank', category: 'Travel', aliases: ['bank'] },
  { emoji: '🏨', name: 'hotel', category: 'Travel', aliases: ['hotel'] },
  { emoji: '🏫', name: 'school', category: 'Travel', aliases: ['school'] },
  { emoji: '⛰️', name: 'mountain', category: 'Travel', aliases: ['mountain'] },
  { emoji: '🏔️', name: 'snow mountain', category: 'Travel', aliases: ['mountain_snow'] },
  { emoji: '🌋', name: 'volcano', category: 'Travel', aliases: ['volcano'] },
  { emoji: '🏖️', name: 'beach', category: 'Travel', aliases: ['beach_with_umbrella', 'beach'] },
  { emoji: '🏝️', name: 'island', category: 'Travel', aliases: ['desert_island', 'island'] },
  { emoji: '🌍', name: 'globe europe africa', category: 'Travel', aliases: ['earth_africa', 'globe'] },
  { emoji: '🌎', name: 'globe americas', category: 'Travel', aliases: ['earth_americas'] },
  { emoji: '🌏', name: 'globe asia australia', category: 'Travel', aliases: ['earth_asia'] },
  { emoji: '🌈', name: 'rainbow', category: 'Travel', aliases: ['rainbow'] },
  { emoji: '☀️', name: 'sun', category: 'Travel', aliases: ['sunny', 'sun'] },
  { emoji: '⛅', name: 'sun behind cloud', category: 'Travel', aliases: ['partly_sunny'] },
  { emoji: '☁️', name: 'cloud', category: 'Travel', aliases: ['cloud'] },
  { emoji: '🌧️', name: 'rain cloud', category: 'Travel', aliases: ['cloud_with_rain', 'rain'] },
  { emoji: '⛈️', name: 'storm', category: 'Travel', aliases: ['thunder_cloud_and_rain', 'storm'] },
  { emoji: '❄️', name: 'snowflake', category: 'Travel', aliases: ['snowflake'] },
  { emoji: '⛄', name: 'snowman', category: 'Travel', aliases: ['snowman'] },
  { emoji: '🌙', name: 'moon', category: 'Travel', aliases: ['crescent_moon', 'moon'] },
  { emoji: '🌊', name: 'ocean wave', category: 'Travel', aliases: ['ocean', 'wave'] },

  // ── Objects & Work ────────────────────────────────────────────────────────
  { emoji: '💻', name: 'laptop', category: 'Objects', aliases: ['computer', 'laptop'] },
  { emoji: '🖥️', name: 'desktop', category: 'Objects', aliases: ['desktop_computer'] },
  { emoji: '⌨️', name: 'keyboard', category: 'Objects', aliases: ['keyboard'] },
  { emoji: '🖱️', name: 'mouse', category: 'Objects', aliases: ['computer_mouse'] },
  { emoji: '🖨️', name: 'printer', category: 'Objects', aliases: ['printer'] },
  { emoji: '📱', name: 'mobile phone', category: 'Objects', aliases: ['iphone', 'phone', 'mobile'] },
  { emoji: '☎️', name: 'telephone', category: 'Objects', aliases: ['telephone', 'phone_classic'] },
  { emoji: '🔋', name: 'battery', category: 'Objects', aliases: ['battery'] },
  { emoji: '🔌', name: 'plug', category: 'Objects', aliases: ['electric_plug', 'plug'] },
  { emoji: '💾', name: 'floppy disk', category: 'Objects', aliases: ['floppy_disk', 'save'] },
  { emoji: '💿', name: 'optical disk', category: 'Objects', aliases: ['cd'] },
  { emoji: '📷', name: 'camera', category: 'Objects', aliases: ['camera'] },
  { emoji: '🎥', name: 'movie camera', category: 'Objects', aliases: ['movie_camera'] },
  { emoji: '📺', name: 'television', category: 'Objects', aliases: ['tv', 'television'] },
  { emoji: '🔍', name: 'magnifying glass', category: 'Objects', aliases: ['mag', 'search', 'zoom'] },
  { emoji: '💡', name: 'light bulb', category: 'Objects', aliases: ['bulb', 'idea'] },
  { emoji: '🔦', name: 'flashlight', category: 'Objects', aliases: ['flashlight'] },
  { emoji: '🕯️', name: 'candle', category: 'Objects', aliases: ['candle'] },
  { emoji: '📖', name: 'open book', category: 'Objects', aliases: ['open_book', 'book'] },
  { emoji: '📚', name: 'books', category: 'Objects', aliases: ['books'] },
  { emoji: '📓', name: 'notebook', category: 'Objects', aliases: ['notebook'] },
  { emoji: '📝', name: 'memo', category: 'Objects', aliases: ['memo', 'pencil'] },
  { emoji: '✏️', name: 'pencil', category: 'Objects', aliases: ['pencil2'] },
  { emoji: '🖊️', name: 'pen', category: 'Objects', aliases: ['pen'] },
  { emoji: '📋', name: 'clipboard', category: 'Objects', aliases: ['clipboard'] },
  { emoji: '📌', name: 'pushpin', category: 'Objects', aliases: ['pushpin'] },
  { emoji: '📍', name: 'round pushpin', category: 'Objects', aliases: ['round_pushpin', 'location'] },
  { emoji: '📎', name: 'paperclip', category: 'Objects', aliases: ['paperclip'] },
  { emoji: '📁', name: 'folder', category: 'Objects', aliases: ['file_folder', 'folder'] },
  { emoji: '📂', name: 'open folder', category: 'Objects', aliases: ['open_file_folder'] },
  { emoji: '📅', name: 'calendar', category: 'Objects', aliases: ['calendar', 'date'] },
  { emoji: '📆', name: 'tear-off calendar', category: 'Objects', aliases: ['calendar_spiral'] },
  { emoji: '📊', name: 'bar chart', category: 'Objects', aliases: ['bar_chart'] },
  { emoji: '📈', name: 'chart up', category: 'Objects', aliases: ['chart_increasing', 'chart_up'] },
  { emoji: '📉', name: 'chart down', category: 'Objects', aliases: ['chart_decreasing', 'chart_down'] },
  { emoji: '📦', name: 'package', category: 'Objects', aliases: ['package'] },
  { emoji: '📣', name: 'megaphone', category: 'Objects', aliases: ['mega', 'megaphone'] },
  { emoji: '📢', name: 'loudspeaker', category: 'Objects', aliases: ['loudspeaker'] },
  { emoji: '💬', name: 'speech bubble', category: 'Objects', aliases: ['speech_balloon'] },
  { emoji: '💭', name: 'thought bubble', category: 'Objects', aliases: ['thought_balloon'] },
  { emoji: '💰', name: 'money bag', category: 'Objects', aliases: ['moneybag', 'money'] },
  { emoji: '💳', name: 'credit card', category: 'Objects', aliases: ['credit_card'] },
  { emoji: '💎', name: 'gem', category: 'Objects', aliases: ['gem', 'diamond'] },
  { emoji: '⚙️', name: 'gear', category: 'Objects', aliases: ['gear', 'settings'] },
  { emoji: '🔧', name: 'wrench', category: 'Objects', aliases: ['wrench'] },
  { emoji: '🔨', name: 'hammer', category: 'Objects', aliases: ['hammer'] },
  { emoji: '🛠️', name: 'hammer and wrench', category: 'Objects', aliases: ['hammer_and_wrench', 'tools'] },
  { emoji: '🔩', name: 'nut and bolt', category: 'Objects', aliases: ['nut_and_bolt'] },
  { emoji: '🧰', name: 'toolbox', category: 'Objects', aliases: ['toolbox'] },
  { emoji: '🔒', name: 'lock', category: 'Objects', aliases: ['lock'] },
  { emoji: '🔓', name: 'unlock', category: 'Objects', aliases: ['unlock'] },
  { emoji: '🔑', name: 'key', category: 'Objects', aliases: ['key'] },
  { emoji: '🗝️', name: 'old key', category: 'Objects', aliases: ['old_key'] },
  { emoji: '⏰', name: 'alarm clock', category: 'Objects', aliases: ['alarm_clock'] },
  { emoji: '⏱️', name: 'stopwatch', category: 'Objects', aliases: ['stopwatch'] },
  { emoji: '⌛', name: 'hourglass done', category: 'Objects', aliases: ['hourglass'] },
  { emoji: '📨', name: 'incoming envelope', category: 'Objects', aliases: ['incoming_envelope'] },
  { emoji: '📧', name: 'email', category: 'Objects', aliases: ['email', 'e-mail'] },
  { emoji: '🎁', name: 'gift', category: 'Objects', aliases: ['gift', 'present'] },
  { emoji: '🎈', name: 'balloon', category: 'Objects', aliases: ['balloon'] },
  { emoji: '🎉', name: 'party popper', category: 'Objects', aliases: ['tada', 'party'] },
  { emoji: '🎊', name: 'confetti', category: 'Objects', aliases: ['confetti_ball'] },

  // ── Symbols ───────────────────────────────────────────────────────────────
  { emoji: '✅', name: 'check mark button', category: 'Symbols', aliases: ['white_check_mark', 'check'] },
  { emoji: '☑️', name: 'check box', category: 'Symbols', aliases: ['ballot_box_with_check'] },
  { emoji: '✔️', name: 'check mark', category: 'Symbols', aliases: ['heavy_check_mark'] },
  { emoji: '❌', name: 'cross mark', category: 'Symbols', aliases: ['x', 'cross_mark'] },
  { emoji: '❎', name: 'cross mark button', category: 'Symbols', aliases: ['negative_squared_cross_mark'] },
  { emoji: '⚠️', name: 'warning', category: 'Symbols', aliases: ['warning'] },
  { emoji: '🚫', name: 'prohibited', category: 'Symbols', aliases: ['no_entry_sign', 'prohibited'] },
  { emoji: '⛔', name: 'no entry', category: 'Symbols', aliases: ['no_entry'] },
  { emoji: '❓', name: 'question', category: 'Symbols', aliases: ['question'] },
  { emoji: '❗', name: 'exclamation', category: 'Symbols', aliases: ['exclamation', 'bangbang'] },
  { emoji: '‼️', name: 'double exclamation', category: 'Symbols', aliases: ['bangbang'] },
  { emoji: '💢', name: 'anger', category: 'Symbols', aliases: ['anger'] },
  { emoji: '♻️', name: 'recycle', category: 'Symbols', aliases: ['recycle'] },
  { emoji: '✳️', name: 'eight spoked asterisk', category: 'Symbols', aliases: ['eight_spoked_asterisk'] },
  { emoji: '✴️', name: 'eight pointed star', category: 'Symbols', aliases: ['eight_pointed_black_star'] },
  { emoji: '🆗', name: 'ok button', category: 'Symbols', aliases: ['ok'] },
  { emoji: '🆕', name: 'new button', category: 'Symbols', aliases: ['new'] },
  { emoji: '🆒', name: 'cool button', category: 'Symbols', aliases: ['cool'] },
  { emoji: '🆓', name: 'free button', category: 'Symbols', aliases: ['free'] },
  { emoji: '🔟', name: 'keycap ten', category: 'Symbols', aliases: ['keycap_ten', '10'] },
  { emoji: '0️⃣', name: 'keycap zero', category: 'Symbols', aliases: ['zero', '0'] },
  { emoji: '1️⃣', name: 'keycap one', category: 'Symbols', aliases: ['one', '1'] },
  { emoji: '2️⃣', name: 'keycap two', category: 'Symbols', aliases: ['two', '2'] },
  { emoji: '3️⃣', name: 'keycap three', category: 'Symbols', aliases: ['three', '3'] },
  { emoji: '4️⃣', name: 'keycap four', category: 'Symbols', aliases: ['four', '4'] },
  { emoji: '5️⃣', name: 'keycap five', category: 'Symbols', aliases: ['five', '5'] },
  { emoji: '6️⃣', name: 'keycap six', category: 'Symbols', aliases: ['six', '6'] },
  { emoji: '7️⃣', name: 'keycap seven', category: 'Symbols', aliases: ['seven', '7'] },
  { emoji: '8️⃣', name: 'keycap eight', category: 'Symbols', aliases: ['eight', '8'] },
  { emoji: '9️⃣', name: 'keycap nine', category: 'Symbols', aliases: ['nine', '9'] },
  { emoji: '🔢', name: 'input numbers', category: 'Symbols', aliases: ['1234', 'numbers'] },
  { emoji: '#️⃣', name: 'keycap hash', category: 'Symbols', aliases: ['hash'] },
  { emoji: '*️⃣', name: 'keycap asterisk', category: 'Symbols', aliases: ['asterisk'] },
  { emoji: '➕', name: 'plus', category: 'Symbols', aliases: ['heavy_plus_sign', 'plus'] },
  { emoji: '➖', name: 'minus', category: 'Symbols', aliases: ['heavy_minus_sign', 'minus'] },
  { emoji: '➗', name: 'divide', category: 'Symbols', aliases: ['heavy_division_sign', 'divide'] },
  { emoji: '✖️', name: 'multiply', category: 'Symbols', aliases: ['heavy_multiplication_x', 'multiply'] },
  { emoji: '💲', name: 'dollar', category: 'Symbols', aliases: ['heavy_dollar_sign', 'dollar'] },
  { emoji: '⭐', name: 'star', category: 'Symbols', aliases: ['star'] },
  { emoji: '🌟', name: 'glowing star', category: 'Symbols', aliases: ['star2', 'glowing_star'] },
  { emoji: '✨', name: 'sparkles', category: 'Symbols', aliases: ['sparkles'] },
  { emoji: '⚡', name: 'high voltage', category: 'Symbols', aliases: ['zap', 'lightning'] },
  { emoji: '🔥', name: 'fire', category: 'Symbols', aliases: ['fire', 'lit'] },
  { emoji: '💥', name: 'boom', category: 'Symbols', aliases: ['boom', 'collision'] },
  { emoji: '💫', name: 'dizzy', category: 'Symbols', aliases: ['dizzy'] },
  { emoji: '🔔', name: 'bell', category: 'Symbols', aliases: ['bell', 'notification'] },
  { emoji: '🔕', name: 'bell with slash', category: 'Symbols', aliases: ['no_bell', 'mute'] },
  { emoji: '🔴', name: 'red circle', category: 'Symbols', aliases: ['red_circle'] },
  { emoji: '🟠', name: 'orange circle', category: 'Symbols', aliases: ['orange_circle'] },
  { emoji: '🟡', name: 'yellow circle', category: 'Symbols', aliases: ['yellow_circle'] },
  { emoji: '🟢', name: 'green circle', category: 'Symbols', aliases: ['green_circle'] },
  { emoji: '🔵', name: 'blue circle', category: 'Symbols', aliases: ['blue_circle'] },
  { emoji: '🟣', name: 'purple circle', category: 'Symbols', aliases: ['purple_circle'] },
  { emoji: '⚫', name: 'black circle', category: 'Symbols', aliases: ['black_circle'] },
  { emoji: '⚪', name: 'white circle', category: 'Symbols', aliases: ['white_circle'] },

  // ── Flags ─────────────────────────────────────────────────────────────────
  { emoji: '🏁', name: 'checkered flag', category: 'Flags', aliases: ['checkered_flag'] },
  { emoji: '🚩', name: 'triangular flag', category: 'Flags', aliases: ['triangular_flag_on_post', 'red_flag'] },
  { emoji: '🏳️', name: 'white flag', category: 'Flags', aliases: ['white_flag'] },
  { emoji: '🏴', name: 'black flag', category: 'Flags', aliases: ['black_flag'] },
  { emoji: '🏳️‍🌈', name: 'rainbow flag', category: 'Flags', aliases: ['rainbow_flag', 'pride'] },
  { emoji: '🏴‍☠️', name: 'pirate flag', category: 'Flags', aliases: ['pirate_flag'] },
  { emoji: '🇹🇭', name: 'thailand', category: 'Flags', aliases: ['th', 'thailand'] },
  { emoji: '🇺🇸', name: 'united states', category: 'Flags', aliases: ['us', 'usa'] },
  { emoji: '🇯🇵', name: 'japan', category: 'Flags', aliases: ['jp', 'japan'] },
  { emoji: '🇬🇧', name: 'united kingdom', category: 'Flags', aliases: ['gb', 'uk'] },
  { emoji: '🇨🇳', name: 'china', category: 'Flags', aliases: ['cn', 'china'] },
  { emoji: '🇰🇷', name: 'south korea', category: 'Flags', aliases: ['kr', 'korea'] },
  { emoji: '🇩🇪', name: 'germany', category: 'Flags', aliases: ['de', 'germany'] },
  { emoji: '🇫🇷', name: 'france', category: 'Flags', aliases: ['fr', 'france'] },
  { emoji: '🇮🇳', name: 'india', category: 'Flags', aliases: ['in', 'india'] },
  { emoji: '🇸🇬', name: 'singapore', category: 'Flags', aliases: ['sg', 'singapore'] },
  { emoji: '🇦🇺', name: 'australia', category: 'Flags', aliases: ['au', 'australia'] },
  { emoji: '🇨🇦', name: 'canada', category: 'Flags', aliases: ['ca', 'canada'] },
  { emoji: '🇻🇳', name: 'vietnam', category: 'Flags', aliases: ['vn', 'vietnam'] },
  { emoji: '🇮🇩', name: 'indonesia', category: 'Flags', aliases: ['id', 'indonesia'] },
  { emoji: '🇲🇾', name: 'malaysia', category: 'Flags', aliases: ['my', 'malaysia'] },
  { emoji: '🇵🇭', name: 'philippines', category: 'Flags', aliases: ['ph', 'philippines'] },
]

export const CATEGORIES = [
  'Smileys',
  'People',
  'Gestures',
  'Hearts',
  'Animals',
  'Food',
  'Activities',
  'Travel',
  'Objects',
  'Symbols',
  'Flags',
] as const

export const CATEGORY_ICONS: Record<string, string> = {
  Smileys: '😀',
  People: '🧑',
  Gestures: '👍',
  Hearts: '❤️',
  Animals: '🐶',
  Food: '🍕',
  Activities: '⚽',
  Travel: '🚗',
  Objects: '💻',
  Symbols: '✅',
  Flags: '🏁',
}

// ── Search matcher (name + colon alias, digit-aware) ──────────────────────
/**
 * Returns true when the emoji matches `query`. Supports plain name search,
 * bare alias search ('thumbsup'), colon-wrapped alias search (':+1:'), and
 * numeric/digit aliases (e.g. '100', '+1', '8ball', '1').
 */
export function emojiMatches(entry: EmojiEntry, query: string): boolean {
  const raw = query.trim().toLowerCase()
  if (!raw) return true
  // Strip surrounding colons so ':+1:' and '+1' behave identically. Digits and
  // symbol characters such as '+', '-' inside the term are preserved.
  const q = raw.replace(/^:+/, '').replace(/:+$/, '')
  if (!q) return true
  if (entry.name.toLowerCase().includes(q)) return true
  if (entry.emoji.includes(q)) return true
  return (entry.aliases || []).some(a => a.toLowerCase().includes(q))
}

// ── Frequently-used emojis (stored in localStorage) ──────────────────────
const FREQ_KEY = 'aaelink-emoji-freq'
const MAX_RECENT = 16

export function getFrequent(): string[] {
  try {
    const raw = localStorage.getItem(FREQ_KEY)
    if (!raw) return []
    return JSON.parse(raw) as string[]
  } catch { return [] }
}

export function pushFrequent(emoji: string) {
  try {
    const cur = getFrequent().filter(e => e !== emoji)
    cur.unshift(emoji)
    localStorage.setItem(FREQ_KEY, JSON.stringify(cur.slice(0, MAX_RECENT)))
  } catch { /* noop */ }
}

// ── Skin-tone selection (stored in localStorage) ─────────────────────────
const TONE_KEY = 'aaelink:emoji:skintone'
// Legacy key read as a fallback so existing preferences migrate gracefully.
const TONE_KEY_LEGACY = 'aaelink-emoji-skin-tone'

/** Fitzpatrick modifier codepoints, indexed 0 (default/none) → 5 (darkest). */
export const SKIN_TONES = [
  { label: 'Default', modifier: '', swatch: '✋' },
  { label: 'Light', modifier: '\u{1F3FB}', swatch: '✋🏻' },
  { label: 'Medium-Light', modifier: '\u{1F3FC}', swatch: '✋🏼' },
  { label: 'Medium', modifier: '\u{1F3FD}', swatch: '✋🏽' },
  { label: 'Medium-Dark', modifier: '\u{1F3FE}', swatch: '✋🏾' },
  { label: 'Dark', modifier: '\u{1F3FF}', swatch: '✋🏿' },
] as const

export function getSkinTone(): number {
  try {
    const raw = localStorage.getItem(TONE_KEY) ?? localStorage.getItem(TONE_KEY_LEGACY)
    if (!raw) return 0
    const n = parseInt(raw, 10)
    return Number.isFinite(n) && n >= 0 && n < SKIN_TONES.length ? n : 0
  } catch { return 0 }
}

export function setSkinTone(idx: number) {
  try {
    localStorage.setItem(TONE_KEY, String(idx))
  } catch { /* noop */ }
}

/**
 * Apply the chosen skin tone to a skin-tonable emoji. A variation selector
 * (U+FE0F) is dropped before appending the modifier so the combination renders
 * correctly. Non-tonable emoji and the default tone are returned unchanged.
 */
export function applySkinTone(entry: EmojiEntry, toneIdx: number): string {
  if (!entry.skinTonable || toneIdx <= 0) return entry.emoji
  const modifier = SKIN_TONES[toneIdx]?.modifier
  if (!modifier) return entry.emoji
  const base = entry.emoji.replace(/️/g, '')
  return base + modifier
}
